### ISSUE TITLE
package gopkg.in/qml.v1/webengine: cannot find package "gopkg.in/qml.v1/webengine"

### ISSUE THREAD

**Issue by pdurbin** [prologic/gopherclient#1]
As discussed at http://irclog.greptilian.com/sourcefu/2016-10-01 based on https://github.com/go-qml/qml/pull/120#issuecomment-244531536 I suspected that an unmerged pull request on go-qml is being used (webengine patch) so @prologic indicated I should open this issue.

**Comment by prologic** [comment]
Thanks @pdurbin ; I had totally forgotten that I locally patched my version of go-qml :/ tsk tsk tsk :)
